# Generated by Django 3.1.2 on 2020-11-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobvacancy',
            options={'verbose_name': 'Job Vacancy', 'verbose_name_plural': 'Job Vacancies'},
        ),
    ]
