# Generated by Django 3.1.2 on 2020-11-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0004_userprofile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_linked', models.ImageField(max_length=1048576, null=True, upload_to='article/images/')),
                ('video_linked', models.FileField(max_length=5242880, null=True, upload_to='article/videos/')),
                ('doc_linked', models.FileField(max_length=2621440, null=True, upload_to='article/docs')),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='userauth.UserProfile')),
                ('wriiten_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wriiten_by', to='userauth.userprofile')),
            ],
        ),
    ]
