# Generated by Django 3.1.2 on 2020-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
