# Generated by Django 3.1.2 on 2020-11-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('downvoter', models.ManyToManyField(blank=True, related_name='celebrate_downvoter', to='userauth.UserProfile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrated', to='post.post')),
                ('upvoter', models.ManyToManyField(blank=True, related_name='celebrate_upvoter', to='userauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Curious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('downvoter', models.ManyToManyField(blank=True, related_name='curious_downvoter', to='userauth.UserProfile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curious', to='post.post')),
                ('upvoter', models.ManyToManyField(blank=True, related_name='curious_upvoter', to='userauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Insightful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('downvoter', models.ManyToManyField(blank=True, related_name='insightful_downvoter', to='userauth.UserProfile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insightful', to='post.post')),
                ('upvoter', models.ManyToManyField(blank=True, related_name='insightful_upvoter', to='userauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('downvoter', models.ManyToManyField(blank=True, related_name='like_downvoter', to='userauth.UserProfile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post')),
                ('upvoter', models.ManyToManyField(blank=True, related_name='like_upvoter', to='userauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('downvoter', models.ManyToManyField(blank=True, related_name='love_downvoter', to='userauth.UserProfile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loves', to='post.post')),
                ('upvoter', models.ManyToManyField(blank=True, related_name='love_upvoter', to='userauth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('downvoter', models.ManyToManyField(blank=True, related_name='support_downvoter', to='userauth.UserProfile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='post.post')),
                ('upvoter', models.ManyToManyField(blank=True, related_name='support_upvoter', to='userauth.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='upvoter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvoter',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='downvoter',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvoter',
        ),
        migrations.DeleteModel(
            name='Downvoter',
        ),
        migrations.DeleteModel(
            name='Upvoter',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
