# Generated by Django 3.1.2 on 2020-11-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.TextField(default='india'),
            preserve_default=False,
        ),
    ]
