# Generated by Django 3.1.2 on 2020-11-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
