# Generated by Django 3.1.2 on 2020-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201112_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='doc_linked',
            field=models.FileField(blank=True, max_length=2621440, null=True, upload_to='article/docs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_linked',
            field=models.ImageField(blank=True, max_length=1048576, null=True, upload_to='article/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_linked',
            field=models.FileField(blank=True, max_length=5242880, null=True, upload_to='article/videos/'),
        ),
    ]
