# Generated by Django 3.1.2 on 2020-11-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
