# Generated by Django 3.1.2 on 2020-11-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('post', '0002_auto_20201112_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='userauth.userprofile'),
        ),
    ]
