# Generated by Django 3.1.2 on 2020-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('post', '0003_auto_20201112_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='userauth.UserProfile'),
        ),
    ]
