# Generated by Django 3.1.2 on 2020-11-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('post', '0003_auto_20201115_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ManyToManyField(null=True, related_name='comments_liked', to='userauth.UserProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.comment')),
                ('liked_by', models.ManyToManyField(null=True, related_name='replies_liked', to='userauth.UserProfile')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
    ]
