# Generated by Django 3.1.2 on 2020-11-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_vot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curious',
            name='downvoter',
        ),
        migrations.RemoveField(
            model_name='curious',
            name='post',
        ),
        migrations.RemoveField(
            model_name='curious',
            name='upvoter',
        ),
        migrations.RemoveField(
            model_name='insightful',
            name='downvoter',
        ),
        migrations.RemoveField(
            model_name='insightful',
            name='post',
        ),
        migrations.RemoveField(
            model_name='insightful',
            name='upvoter',
        ),
        migrations.RemoveField(
            model_name='like',
            name='downvoter',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='upvoter',
        ),
        migrations.RemoveField(
            model_name='love',
            name='downvoter',
        ),
        migrations.RemoveField(
            model_name='love',
            name='post',
        ),
        migrations.RemoveField(
            model_name='love',
            name='upvoter',
        ),
        migrations.RemoveField(
            model_name='support',
            name='downvoter',
        ),
        migrations.RemoveField(
            model_name='support',
            name='post',
        ),
        migrations.RemoveField(
            model_name='support',
            name='upvoter',
        ),
        migrations.DeleteModel(
            name='Celebrate',
        ),
        migrations.DeleteModel(
            name='Curious',
        ),
        migrations.DeleteModel(
            name='Insightful',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Love',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
