# Generated by Django 3.1.2 on 2020-11-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('post', '0005_auto_20201113_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'like'), ('celebrate', 'celebrate'), ('support', 'support'), ('love', 'love'), ('insightful', 'insightful'), ('curious', 'curious')], default=None, max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='userauth.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Vot',
        ),
    ]
