# Generated by Django 3.1.2 on 2020-11-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201125_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
