# Generated by Django 3.1.2 on 2020-11-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('post_liked', 'post_liked'), ('comment_liked', 'comment_liked'), ('reply_liked', 'reply_liked'), ('commented', 'commented'), ('viewed', 'viewed'), ('replied', 'replied'), ('application_accepted', 'application_accepted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
                ('action_id', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_made', to='userauth.userprofile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='userauth.userprofile')),
            ],
        ),
    ]
