# Generated by Django 3.1.2 on 2020-11-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201128_1307'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'follower')},
        ),
    ]
