# Generated by Django 3.1.2 on 2020-11-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201124_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='network',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
