# Generated by Django 3.1.2 on 2020-11-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
