# Generated by Django 3.1.2 on 2020-11-12 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_delete_follow'),
        ('network', '0004_auto_20201112_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='userauth.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='followers',
            field=models.ManyToManyField(blank=True, to='userauth.UserProfile'),
        ),
    ]
