# Generated by Django 3.1.2 on 2020-11-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201112_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
