# Generated by Django 3.1.2 on 2020-11-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=500)),
                ('file', models.FileField(blank=True, max_length=10485760, null=True, upload_to='chat/')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_msgs', to='userauth.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to='userauth.userprofile')),
            ],
            options={
                'ordering': ('-time_created',),
            },
        ),
    ]
