# Generated by Django 3.1.2 on 2020-11-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('chat', '0003_remove_chat_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='members',
        ),
        migrations.AddField(
            model_name='thread',
            name='first_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_first', to='userauth.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='second_member',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='member_second', to='userauth.userprofile'),
            preserve_default=False,
        ),
    ]
