# Generated by Django 3.1.2 on 2020-11-12 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('cause', models.CharField(choices=[('Animal Welfare', 'Animal Welfare'), ('Arts and Culture', 'Arts and Culture'), ('Children', 'Children'), ('Civil Rights and Social Action', 'Civil Rights and Social Action'), ('Economic Empowerment', 'Economic Empowerment'), ('Education', 'Education'), ('Environment', 'Environment'), ('Health', 'Health'), ('Human Rights', 'Human Rights'), ('Politics', 'Politics'), ('Poverty Alleviation', 'Poverty Alleviation'), ('Veteran Support', 'Veteran Support'), ('Social Services', 'Social Services'), ('Science and Technology', 'Science and Technology')], default=None, max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_experience', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Volunteer Experience',
                'verbose_name_plural': 'Volunteer Experiences',
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_organization', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Test Score',
                'verbose_name_plural': 'Test Scores',
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=20, null=True)),
                ('background_photo', models.ImageField(blank=True, max_length=1048576, null=True, upload_to='background/')),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('profile_url', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Social Profile',
                'verbose_name_plural': 'Social Profiles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_list', multiselectfield.db.fields.MultiSelectField(choices=[('Tools & Technology', (('C++', 'C++'), ('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('Flutter', 'Flutter'), ('React', 'React'), ('Android Development', 'Android Development'), ('Angular', 'Angular'), ('Flask', 'Flask'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SASS', 'SASS'), ('Bootstrap', 'Bootstrap'), ('Ruby', 'Ruby'), ('C#', 'C#'), ('Spring', 'Spring'), ('Laraval', 'Laraval'), ('PHP', 'PHP'), ('Node', 'Node'), ('Git', 'Git'), ('GitHub', 'GitHub'), ('ASP.NET', 'ASP.NET'), ('Machine Learning', 'Machine Learning'), ('Big Data', 'Big Data'))), ('Interpersonal', (('Leadership', 'Leadership'), ('Team Management', 'Team Management'), ('Resource Management', 'Resource Management'), ('Team Building', 'Team Building'), ('Teamwork', 'Teamwork'), ('Public Speaking', 'Public Speaking'), ('Communication', 'Communication'), ('Writing', 'Writing'), ('Collaborative Problem Solving', 'Collaborative Problem Solving'), ('Strategic Negotiations', 'Strategic Negotiations'), ('Customer Service', 'Customer Service')))], max_length=300)),
                ('top_skills', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('organization_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_organization', to='organization.organization')),
                ('user', models.ManyToManyField(blank=True, related_name='project', to='userauth.UserProfile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='LicenseAndCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('credential_id', models.TextField(blank=True, max_length=30, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'License And Certification',
                'verbose_name_plural': 'License And Certifications',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Academic ',
                'verbose_name_plural': 'Academics',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('passed_date', models.DateField(default=datetime.date.today)),
                ('organization_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_taken', to='userauth.userprofile')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
