# Generated by Django 3.1.2 on 2020-11-12 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='current_academic',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_academic', to='profile.education'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='current_organization',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_work', to='profile.workexperience'),
        ),
    ]
