# Generated by Django 3.1.2 on 2020-11-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='object_id',
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='current_academia',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_academic', to='profile.education'),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='current_industry',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_work', to='profile.workexperience'),
        ),
    ]
