# Generated by Django 3.1.2 on 2020-11-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsement', to='profile.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_skills', to='userauth.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='endorsed_by',
            field=models.ManyToManyField(through='profile.Endorsement', to='userauth.UserProfile'),
        ),
    ]
