# Generated by Django 3.1.2 on 2020-11-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('profile', '0002_auto_20201117_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='external_site_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, to='userauth.UserProfile'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='userauth.userprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profile.jobvacancy')),
            ],
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='applied_by',
            field=models.ManyToManyField(related_name='jobs_applied_to', through='profile.JobApplication', to='userauth.UserProfile'),
        ),
    ]
