# Generated by Django 3.1.2 on 2020-11-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='my_field2',
        ),
    ]
