# Generated by Django 3.1.2 on 2020-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20201114_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
