# Generated by Django 3.1.2 on 2020-11-12 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_userprofile_followers'),
        ('profile', '0002_auto_20201112_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=20, null=True)),
                ('background_photo', models.ImageField(blank=True, max_length=1048576, null=True, upload_to='background/')),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('profile_url', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to='userauth.userprofile')),
            ],
        ),
    ]
