# Generated by Django 3.1.2 on 2020-11-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20201113_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialprofile',
            old_name='current_academic',
            new_name='current_academic_organization',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='current_organization',
            new_name='current_work_organization',
        ),
    ]
