# Generated by Django 3.1.2 on 2020-11-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20201113_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='current_academic_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_academic', to='profile.education'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='current_work_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_work', to='profile.workexperience'),
        ),
    ]
