# Generated by Django 3.1.2 on 2020-11-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_socialprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'verbose_name': 'Social Profile', 'verbose_name_plural': 'Social Profiles'},
        ),
    ]
