# Generated by Django 3.1.2 on 2020-11-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('profile', '0003_auto_20201117_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvacancy',
            old_name='applied_by',
            new_name='applicants',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='remarks',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.jobvacancy'),
        ),
    ]
