# Generated by Django 3.1.2 on 2020-11-14 17:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_skill_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills_list',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tools & Technology', (('C++', 'C++'), ('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('Flutter', 'Flutter'), ('React', 'React'), ('Android Development', 'Android Development'), ('Angular', 'Angular'), ('Flask', 'Flask'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SASS', 'SASS'), ('Bootstrap', 'Bootstrap'), ('Ruby', 'Ruby'), ('C#', 'C#'), ('Spring', 'Spring'), ('Laraval', 'Laraval'), ('PHP', 'PHP'), ('Node', 'Node'), ('Git', 'Git'), ('GitHub', 'GitHub'), ('ASP.NET', 'ASP.NET'), ('Machine Learning', 'Machine Learning'), ('Big Data', 'Big Data'))), ('Interpersonal', (('Leadership', 'Leadership'), ('Team Management', 'Team Management'), ('Resource Management', 'Resource Management'), ('Team Building', 'Team Building'), ('Teamwork', 'Teamwork'), ('Public Speaking', 'Public Speaking'), ('Communication', 'Communication'), ('Writing', 'Writing'), ('Collaborative Problem Solving', 'Collaborative Problem Solving'), ('Strategic Negotiations', 'Strategic Negotiations'), ('Customer Service', 'Customer Service')))], max_length=300, null=True),
        ),
    ]
