# Generated by Django 3.1.2 on 2020-11-08 09:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20201108_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='my_field',
        ),
        migrations.AddField(
            model_name='skills',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Technical', (('item_key1', 'Item title 1.1'), ('item_key1', 'Item title 1.1'), ('item_key1', 'Item title 1.11'))), ('item_key2', 'Item title 1.2')], default=None, max_length=19),
            preserve_default=False,
        ),
    ]
