# Generated by Django 3.1.2 on 2020-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20201117_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='file_linked',
            field=models.FileField(blank=True, max_length=1048576, null=True, upload_to='user/jobs'),
        ),
    ]
