# Generated by Django 3.1.2 on 2020-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20201114_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills_list',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
