# Generated by Django 3.1.2 on 2020-11-08 09:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20201108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Technical', (('Django', 'Django'), ('Python', 'Python'), ('C++', 'C++'))), ('Team Leadership', 'Team Leadership')], max_length=25),
        ),
    ]
