# Generated by Django 3.1.2 on 2020-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20201113_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerexperience',
            name='cause',
            field=models.CharField(choices=[(None, None), ('Animal Welfare', 'Animal Welfare'), ('Arts and Culture', 'Arts and Culture'), ('Children', 'Children'), ('Civil Rights and Social Action', 'Civil Rights and Social Action'), ('Economic Empowerment', 'Economic Empowerment'), ('Education', 'Education'), ('Environment', 'Environment'), ('Health', 'Health'), ('Human Rights', 'Human Rights'), ('Politics', 'Politics'), ('Poverty Alleviation', 'Poverty Alleviation'), ('Veteran Support', 'Veteran Support'), ('Social Services', 'Social Services'), ('Science and Technology', 'Science and Technology')], default=None, max_length=50),
        ),
    ]
