# Generated by Django 3.1.2 on 2020-11-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20201117_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='industry',
            field=models.CharField(default='q', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='payscale',
            field=models.CharField(default='q', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='employment_type',
            field=models.CharField(choices=[('Fulltime', 'Full-Time'), ('Parttime', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Volunteer', 'Volunteer'), ('Temporary', 'Temporary')], max_length=50),
        ),
    ]
