# Generated by Django 3.1.2 on 2020-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('profile', '0007_auto_20201108_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
