# Generated by Django 3.1.2 on 2020-11-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('profile', '0008_auto_20201109_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='userauth.userprofile'),
        ),
    ]
