# Generated by Django 3.1.2 on 2020-11-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20201117_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvacancy',
            old_name='payscale',
            new_name='pay_range',
        ),
    ]
