# Generated by Django 3.1.2 on 2020-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20201117_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='pay_range',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
