# Generated by Django 3.1.2 on 2020-11-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='userauth.userprofile')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='comments_liked', to='userauth.UserProfile')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_linked', models.ImageField(blank=True, max_length=1048576, null=True, upload_to='article/images/')),
                ('video_linked', models.FileField(blank=True, max_length=5242880, null=True, upload_to='article/videos/')),
                ('doc_linked', models.FileField(blank=True, max_length=2621440, null=True, upload_to='article/docs')),
                ('media_type', models.CharField(max_length=6, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='userauth.UserProfile')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='userauth.userprofile')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'like'), ('celebrate', 'celebrate'), ('support', 'support'), ('love', 'love'), ('insightful', 'insightful'), ('curious', 'curious')], default=None, max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='post.post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='userauth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.comment')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='replies_liked', to='userauth.UserProfile')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_made', to='userauth.userprofile')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
    ]
