# Generated by Django 3.1.2 on 2020-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationExperience',
            new_name='Education',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education Experience', 'verbose_name_plural': 'Education Experiences'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
    ]
