# Generated by Django 3.1.2 on 2020-11-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201105_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Academic ', 'verbose_name_plural': 'Academics'},
        ),
    ]
