# Generated by Django 3.1.2 on 2020-10-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='end_year',
            field=models.DateField(blank=True),
        ),
    ]
