# Generated by Django 3.1.2 on 2020-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Employed', 'Employed')], default=None, max_length=35),
        ),
    ]
