# Generated by Django 3.1.2 on 2020-11-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='has_accepted',
            new_name='is_accepted',
        ),
    ]
