# Generated by Django 3.1.2 on 2020-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_followers_+', to='userauth.UserProfile'),
        ),
    ]
