# Generated by Django 3.1.2 on 2020-11-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201112_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
