# Generated by Django 3.1.2 on 2020-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Employed', 'Employed')], max_length=35),
        ),
    ]
