# Generated by Django 3.1.2 on 2020-10-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201026_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_connection_+', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
