# Generated by Django 3.1.2 on 2020-11-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201114_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='start_date',
        ),
    ]
