# Generated by Django 3.1.2 on 2020-10-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201023_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='UserExperience',
        ),
    ]
