# Generated by Django 3.1.2 on 2020-11-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201103_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='userauth.userprofile'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_request_sent', to='userauth.userprofile'),
        ),
    ]
