# Generated by Django 3.1.2 on 2020-11-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20201103_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='is_accepted',
            new_name='has_accepted',
        ),
    ]
