# Generated by Django 3.1.2 on 2020-10-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20201023_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
