# Generated by Django 3.1.2 on 2020-11-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20201103_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='has_accepted',
            new_name='has_been_accepted',
        ),
    ]
