# Generated by Django 3.1.2 on 2020-11-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20201103_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
