# Generated by Django 3.1.2 on 2020-11-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_connection_is_visible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
